### ISSUE TITLE
Problems when using GEOS-FP data processing software

### ISSUE THREAD

**Issue by ChangpeiHe** [geoschem/GEOS_FP#4]
Name: Changpei, He
Institution: Tsinghua University

I Confirm that I have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

I‘m trying to process GEOS-FP raw data to GEOS-Chem input data by GEOS-FP data processing software (https://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-FP_data_processing_software), and I have successfully downloaded the required GEOS-FP  raw files on March 1, 2024, and installed the software according to the user manual.

However, when I run './doGeosFpMulti 20240301', error messages occur as follows:

```console
doGeosFpMulti: All files present!  Now processing met for 20240301!
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP Code stopped from Do_Err_Out.
Global symbol "$DO_05x06125" requires explicit package name at ./moveGeosFp line 303.
Missing right curly or square bracket at ./moveGeosFp line 1004, at end of line
syntax error at ./moveGeosFp line 1004, at EOF
Execution of ./moveGeosFp aborted due to compilation errors.
```

Looking forward to your reply!

**Comment by yantosca** [comment]
Thanks for writing @ChangpeiHe.  I think the issue has been fixed in commit c2ac5e8f3, but this hasn't been merged back into main yet.  You can get this update with:

```console
$ git checkout GEOSFP-fixErrors-Nov3-2023
```

**Comment by yantosca** [comment]
Also tagging @msulprizio

**Comment by ChangpeiHe** [comment]
Thanks for your prompt reply! When I use 'GEOSFP-fixErrors-Nov3-2023 version', new error occurred:
Not enough raw met files for 20240301!

I confirmed that I have downloaded enough data files for 20240301, to derive _**global 2*2.5 met files:**_
['GEOS.fp.asm.tavg3_3d_mst_Ne.20240301_0430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1330.V01.nc4', 'GEOS.fp.asm.tavg3_3d_rad_Nv.20240301_0430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_2130.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Ne.20240301_0730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_2030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1330.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1030.V01.nc4', 'GEOS.fp.asm.tavg3_3d_rad_Nv.20240301_2230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0330.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_2230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_2130.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0130.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_2330.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1130.V01.nc4', 'GEOS.fp.asm.tavg3_3d_rad_Nv.20240301_0130.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1530.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Ne.20240301_1030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_2130.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1730.V01.nc4', 'GEOS.fp.asm.tavg3_3d_rad_Nv.20240301_1930.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0630.V01.nc4', 'GEOS.fp.asm.inst3_3d_asm_Nv.20240301_0600.V01.nc4', 'GEOS.fp.asm.tavg3_3d_cld_Nv.20240301_1030.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Nv.20240301_0130.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Nv.20240301_1030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_2230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0730.V01.nc4', 'GEOS.fp.asm.inst3_3d_asm_Nv.20240301_1200.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Nv.20240301_1630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0130.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0930.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0330.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0530.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1130.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0930.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1930.V01.nc4', 'GEOS.fp.asm.tavg3_3d_cld_Nv.20240301_1930.V01.nc4', 'GEOS.fp.asm.inst3_3d_asm_Nv.20240301_0300.V01.nc4', 'GEOS.fp.asm.tavg3_3d_rad_Nv.20240301_0730.V01.nc4', 'GEOS.fp.asm.tavg3_3d_cld_Nv.20240301_1630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0130.V01.nc4', 'GEOS.fp.asm.tavg3_3d_cld_Nv.20240301_2230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1830.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1930.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0530.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0930.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0930.V01.nc4', 'GEOS.fp.asm.tavg3_3d_cld_Nv.20240301_0430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_2330.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Ne.20240301_1630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1430.V01.nc4', 'GEOS.fp.asm.tavg3_3d_cld_Nv.20240301_0730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1130.V01.nc4', 'GEOS.fp.asm.tavg3_3d_asm_Nv.20240301_0430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_2230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0530.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1330.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0330.V01.nc4', 'GEOS.fp.asm.tavg3_3d_asm_Nv.20240301_1030.V01.nc4', 'GEOS.fp.asm.tavg3_3d_rad_Nv.20240301_1030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1930.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0530.V01.nc4', 'GEOS.fp.asm.tavg3_3d_asm_Nv.20240301_1330.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0030.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Nv.20240301_2230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1830.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1830.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_2030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0330.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_2330.V01.nc4', 'GEOS.fp.asm.inst3_3d_asm_Nv.20240301_1800.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Nv.20240301_1330.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1130.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1230.V01.nc4', 'GEOS.fp.asm.inst3_3d_asm_Nv.20240301_1500.V01.nc4', 'GEOS.fp.asm.tavg3_3d_rad_Nv.20240301_1630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1530.V01.nc4', 'GEOS.fp.asm.tavg3_3d_asm_Nv.20240301_0730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_2030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_2130.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0830.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_2030.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1330.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0830.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0130.V01.nc4', 'GEOS.fp.asm.tavg3_3d_asm_Nv.20240301_2230.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Ne.20240301_0130.V01.nc4', 'GEOS.fp.asm.tavg3_3d_asm_Nv.20240301_0130.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Ne.20240301_1930.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0030.V01.nc4', 'GEOS.fp.asm.tavg3_3d_asm_Nv.20240301_1930.V01.nc4', 'GEOS.fp.asm.tavg3_3d_rad_Nv.20240301_1330.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Nv.20240301_0430.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1930.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Ne.20240301_2230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_0830.V01.nc4', 'GEOS.fp.asm.tavg3_3d_cld_Nv.20240301_0130.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_0730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_0230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_1530.V01.nc4', 'GEOS.fp.asm.tavg3_3d_asm_Nv.20240301_1630.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_1830.V01.nc4', 'GEOS.fp.asm.inst3_3d_asm_Nv.20240301_0900.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0230.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_1630.V01.nc4', 'GEOS.fp.asm.inst3_3d_asm_Nv.20240301_2100.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Ne.20240301_1330.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Nv.20240301_0730.V01.nc4', 'GEOS.fp.asm.tavg1_2d_flx_Nx.20240301_1530.V01.nc4', 'GEOS.fp.asm.tavg1_2d_lnd_Nx.20240301_2230.V01.nc4', 'GEOS.fp.asm.tavg3_3d_mst_Nv.20240301_1930.V01.nc4', 'GEOS.fp.asm.tavg1_2d_slv_Nx.20240301_0830.V01.nc4', 'GEOS.fp.asm.tavg1_2d_rad_Nx.20240301_2330.V01.nc4', 'GEOS.fp.asm.inst3_3d_asm_Nv.20240301_0000.V01.nc4', 'GEOS.fp.asm.tavg3_3d_cld_Nv.20240301_1330.V01.nc4']

==> Local Raw Data Path
/public3/home/sc33074/data/GEOS/tmp/2024/20240301/

**Comment by ChangpeiHe** [comment]
It's strange that in the main branch version, the output information showed that data files on 20240301 appear to be enough.

**_doGeosFpMulti: All files present!  Now processing met for 20240301!_**
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP Code stopped from Do_Err_Out.
Global symbol "$DO_05x06125" requires explicit package name at ./moveGeosFp line 303.
Missing right curly or square bracket at ./moveGeosFp line 1004, at end of line
syntax error at ./moveGeosFp line 1004, at EOF
Execution of ./moveGeosFp aborted due to compilation errors.
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP Code stopped from Do_Err_Out.
Global symbol "$DO_05x06125" requires explicit package name at ./moveGeosFp line 303.
Missing right curly or square bracket at ./moveGeosFp line 1004, at end of line
syntax error at ./moveGeosFp line 1004, at EOF
Execution of ./moveGeosFp aborted due to compilation errors.
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP Code stopped from Do_Err_Out.
Global symbol "$DO_05x06125" requires explicit package name at ./moveGeosFp line 303.
Missing right curly or square bracket at ./moveGeosFp line 1004, at end of line
syntax error at ./moveGeosFp line 1004, at EOF
Execution of ./moveGeosFp aborted due to compilation errors.

**Comment by ChangpeiHe** [comment]
@msulprizio, @yantosca. Looking forward to your reply. This software is invaluable for our team to simulate NRT pm2.5, driven by GEOS-FP. Thanks!

Best regards,
Changpei

**Comment by msulprizio** [comment]
Hi @ChangpeiHe. We have not utilized this code at Harvard in quite some time since the met processing has been transferred to WashU. I'm tagging @yidant in case she has any debugging tips here.

**Comment by msulprizio** [comment]
@ChangpeiHe You could also try reverting to the GEOS_FP code before additional nested domains were added in. The GEOS_FP code should have been working then. You can do: `git checkout 91c85cc83 debug` to checkout a branch called `debug` at commit https://github.com/geoschem/GEOS_FP/commit/91c85cc831ac75e366dc7b89595a2e69874e4b06.

**Comment by ChangpeiHe** [comment]
Thanks for your reply. I tried the older version at commit 91c85cc83 just now. There was only one error left:

"doGeosFpMulti: All files present!  Now processing met for 20240301!
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
STOP Code stopped from Do_Err_Out."

![image](https://github.com/geoschem/GEOS_FP/assets/126058879/1abfbfe6-23f8-4209-aca0-5789ba98e466)

**Comment by ChangpeiHe** [comment]
I reinstalled the software package and used the  commit https://github.com/geoschem/GEOS_FP/commit/91c85cc831ac75e366dc7b89595a2e69874e4b06. It works! Thanks for your prompt reply!
